#!/bin/sh
#
## the snippet for getting ruby bootstrapped

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@"
    rbenv rehash
  fi
}

fancy_echo "Installing rbenv"
# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.rbenv/bin:$PATH"'
# shellcheck disable=SC2016
append_to_zshrc 'eval "$(rbenv init - --no-rehash)"' 1
PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
eval "$(rbenv init -)"

fancy_echo "Configuring Ruby ..."
ruby_version=$(rbenv install -l | grep -v - | tail -1 | sed -e 's/^ *//')
# shellcheck disable=SC2016

if ! rbenv versions | grep -Fq "$ruby_version"; then rbenv install -s "$ruby_version"; fi

rbenv global "$ruby_version"
rbenv shell "$ruby_version"
gem update --system
gem_install_or_update 'bundler'
number_of_cores=$(nproc);
bundle config --global jobs $((number_of_cores - 1))
