#!/bin/sh

# Welcome to the laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
  printf "\n%s\n" "$1";
}

append_to_zshrc() {
  text="$1"
  skip_new_line="${2:-0}"

  zshrc="$HOME/.zshrc"

  if ! grep -Fqs "$text" "$zshrc"; then
    [ "$skip_new_line" -ne 1 ] && printf "\n" >> "$zshrc";
    printf "%s\n" "$text" >> "$zshrc"
  fi
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

fancy_echo "Update Apt Cache"
sudo apt update

fancy_echo "Distro Upgrade"
sudo apt dist-upgrade

sudo apt install -y \
  build-essential \
  zsh \
  exuberant-ctags \
  gcc \
  git \
  htop \
  hub \
  imagemagick \
  openssl \
  libssl-dev \
  zlib1g-dev \
  silversearcher-ag \
  tmate \
  tmux \
  vim \
  xclip

sudo snap install --classic \
  slack \
  code
sudo snap install \
  spotify \
  chromium \
  docker

mkdir -p "$HOME/.bin";
touch "$HOME/.zshrc";

# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

shell_path="$(command -v zsh)"
fancy_echo "Changing your shell to zsh at '$shell_path' ..."
if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
  fancy_echo "Adding '$shell_path' to /etc/shells"
  sudo sh -c "echo $shell_path >> /etc/shells"
fi
sudo chsh -s "$shell_path" "$USER"

fancy_echo "Install nodenv"
curl -fsSL https://raw.githubusercontent.com/nodenv/nodenv-installer/master/bin/nodenv-installer | bash

# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.nodenv/bin:$PATH"'
# shellcheck disable=SC2016
append_to_zshrc 'eval "$(nodenv init -)"' 1

PATH="$HOME/.nodenv/bin:$HOME/.nodenv/shims:$PATH"
eval "$(nodenv init -)"
