name: PSScriptAnalyzer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  psscriptanalyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
          Invoke-ScriptAnalyzer -Path windows -Severity Error
